id: P009602
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90025
  title: ཟུང་ཆུ་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    6bbd98fa27764cb6a22036ac542dd47c:
      image_group_id: I1PD90096
      title: ''
      volume_number: 1
      total_pages: 1108
      base_file: v001.txt
